version: '3'

services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile
    image: jwansek/reversesshtunnel
    network_mode: host
    volumes:
      - /dev/tty:/dev/tty
      - ./vps.pem:/app/vps.pem
      - ./tunnel.conf:/app/tunnel.conf
